### ISSUE TITLE
SeattleGENI emails user input to admin on error without encryption.

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/clearinghouse#81]
When there is an internal error in the SeattleGENI website, the error along with the query dict is emailed to developers and it does not encrypt the passwords of the user. For example I got a 500 internal server error on the login page of SeattleGENI and received an email from seattle.devel@gmail.com (since I am one of the admins of SeattleGENI) and a plain text version of all my input was included in the email.

**Comment by aaaaalbert** [comment]
Workaround in https://github.com/SeattleTestbed/clearinghouse/blob/1f906d9ed1f86a16f2bcaaaa6d2123fac1f8b081/common/util/decorators.py#L211 . The proposed Django-based solution doesn't seem to be implemented though, https://github.com/django/django/commit/45e55b9143

**Comment by aaaaalbert** [comment]
The workaround doesn't cover (at least) this one case:
(I sanitized username, password and IP address)

```
Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response

 File "/home/clearinghouse/live/seattlegeni/website/html/views.py", line 426, in login

 File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 85, in delete_test_cookie

 File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 54, in __delitem__

KeyError: 'testcookie'


<ModPythonRequest
path:/html/login,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'username': [u'..............'], u'csrfmiddlewaretoken': [u'32c8a6757a2bc095b1995dec714a0061'], u'password': [u'.................'], u'jsenabled': [u'true'], u'next': [u'']}>,
COOKIES:{'csrftoken': '32c8a6757a2bc095b1995dec714a0061',
'sessionid': 'd5a26081ccc689ef9b2ee0034e09ceca'},
META:{'AUTH_TYPE': None,
'CONTENT_LENGTH': '106',
'CONTENT_TYPE': 'application/x-www-form-urlencoded',
'CSRF_COOKIE': '32c8a6757a2bc095b1995dec714a0061',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
'HTTP_ACCEPT_LANGUAGE': 'de,en-US;q=0.7,en;q=0.3',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_CONTENT_LENGTH': '106',
'HTTP_CONTENT_TYPE': 'application/x-www-form-urlencoded',
'HTTP_COOKIE': 'csrftoken=32c8a6757a2bc095b1995dec714a0061; sessionid=d5a26081ccc689ef9b2ee0034e09ceca',
'HTTP_DNT': '1',
'HTTP_HOST': 'seattleclearinghouse.poly.edu',
'HTTP_REFERER': 'https://seattleclearinghouse.poly.edu/html/login',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:37.0) Gecko/20100101 Firefox/37.0',
'PATH_INFO': u'/html/login',
'PATH_TRANSLATED': None,
'QUERY_STRING': None,
'REMOTE_ADDR': '...............',
'REMOTE_HOST': None,
'REMOTE_IDENT': None,
'REMOTE_USER': None,
'REQUEST_METHOD': 'POST',
'SCRIPT_NAME': '',
'SERVER_NAME': 'www.seattleclearinghouse.poly.edu',
'SERVER_PORT': 443,
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SOFTWARE': 'mod_python'}>
```
