### ISSUE TITLE
SeattleGENI throws error when logging in without logging out from django admin user

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/clearinghouse#82]
If a user is logged in to the django admin site and then tries to log in as a seattle user on SeattleGENI the site throws an error, and the admins get sent an email. I have attached the traceback sent by the email below:

```
Traceback (most recent call last):

 File "/usr/local/lib/python2.5/site-packages/django/core/handlers/base.py", line 92, in get_response

 File "/home/geni/live/seattlegeni/website/html/views.py", line 275, in login

 File "/usr/local/lib/python2.5/site-packages/django/contrib/sessions/backends/base.py", line 84, in delete_test_cookie

 File "/usr/local/lib/python2.5/site-packages/django/contrib/sessions/backends/base.py", line 53, in __delitem__

KeyError: 'testcookie'


<ModPythonRequest
path:/geni/html/login,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'username': [u'SOME_PASSWORD': [u'12345'](u'SOME_USER'],), u'jsenabled': [u'next': [u''](u'true'],)}>,
COOKIES:{'__utma': '59807807.1177940610.1253592868.1279473699.1283994999.11',
 '__utmz': '59807807.1279473699.10.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)',
 'sessionid': '85546c16c47118a30bb3b495168e645d'},
META:{'AUTH_TYPE': None,
 'CONTENT_LENGTH': 0L,
 'CONTENT_TYPE': None,
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_CHARSET': 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
 'HTTP_ACCEPT_ENCODING': 'gzip,deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-us,en;q=0.5',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_CONTENT_LENGTH': '52',
 'HTTP_CONTENT_TYPE': 'application/x-www-form-urlencoded',
 'HTTP_COOKIE': '__utma=80390417.2340364318866585000.1229466863.1278591968.1284851244.19; __utma=59807807.1177940610.1253592868.1279473699.1283994999.11; __utmz=80390417.1278591968.18.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=eGC1; __utmz=59807807.1279473699.10.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); sessionid=85546c16c47118a30bb3b495168e645d',
 'HTTP_HOST': 'seattlegeni.cs.washington.edu',
 'HTTP_KEEP_ALIVE': '115',
 'HTTP_REFERER': 'https://seattlegeni.cs.washington.edu/geni/html/login',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.4; en-US; rv:1.9.2.10) Gecko/20100914 Firefox/3.6.10',
 'PATH_INFO': u'/html/login',
 'PATH_TRANSLATED': None,
 'QUERY_STRING': None,
 'REMOTE_ADDR': '208.51.118.2',
 'REMOTE_HOST': None,
 'REMOTE_IDENT': None,
 'REMOTE_USER': None,
 'REQUEST_METHOD': 'POST',
 'SCRIPT_NAME': '/geni',
 'SERVER_NAME': 'seattlegeni.cs.washington.edu',
 'SERVER_PORT': 443,
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'mod_python'}>
```

**Comment by aaaaalbert** [comment]
My browser's web devel console shows this: When first loggin in at the clearinghouse under a normal user account, and then logging in at the Django administration backend, the CSRF token for the latter is then also used for interactions with the former.

I consider this a problem *not worth fixing* though, because

* only CH operators interact with the Django admin page in the first place, no random users;
* interactions are infrequent;
* the CH [shows an error message](https://github.com/SeattleTestbed/clearinghouse/blob/master/website/html/views.py#L1162-L1166) pointing out the issue, and
* you can use a private browser tab to work around the problem.

Conclusion: Closing as WONTFIX.
